---
driver:
  name: vagrant
  synced_folders:
    - ["./", "/var/www/cookbooks"]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[ruby_build]
      - recipe[rbenv::user]
      - recipe[test-cookbook]
    attributes:
